# Generated by Django 5.0.2 on 2024-02-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('descr', models.TextField(blank=True)),
            ],
        ),
    ]
