# Generated by Django 5.0.2 on 2024-02-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_poslannik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='category',
            field=models.IntegerField(default=1, verbose_name='cat'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
